name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Make scripts executable
        run: chmod +x skel.sh test.sh

      - name: Run tests
        run: ./test.sh